# Generated by Django 6.0.1 on 2026-03-26 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StudentPerformance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('gender', models.CharField(max_length=20)),
                ('math_score', models.FloatField(default=0)),
                ('science_score', models.FloatField(default=0)),
                ('english_score', models.FloatField(default=0)),
                ('average_score', models.FloatField(blank=True, default=0)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Student Performance',
                'verbose_name_plural': 'Student Performances',
                'ordering': ['-uploaded_at'],
            },
        ),
    ]
