# Generated by Django 6.0.1 on 2026-03-26 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentperformance',
            name='english_score',
        ),
        migrations.RemoveField(
            model_name='studentperformance',
            name='math_score',
        ),
        migrations.RemoveField(
            model_name='studentperformance',
            name='science_score',
        ),
        migrations.AddField(
            model_name='studentperformance',
            name='subjects',
            field=models.JSONField(default=dict, help_text='Dict of subject_name: score'),
        ),
    ]
